24 = +/ score & > boggle 4 4 $ 'DEMODEMODEMODEMO'
1254 = # boggle 4 4 $ 'PSLMEAIARNTRGESO'
189 = # boggle 8 2 $ 'PSLMEAIARNTRGESO'
318 = # boggle 4 4 $ 'YVUPESTAGOLEOWNV'
8 = # boggle 2 2 $ 'ABBA'
25 = # boggle 3 2 $ 'GOOGLE'
(<'JINGO') e. boggle 4 4 board 'jingo'
(<'LAMBAST') e. boggle 4 4 board 'lambast'
(<'INERTIA') e. boggle 4 4 board 'inertia'
(<'HYPNOTIZABILITY') e. boggle 4 4 board 'HYPNOTIZABILITY'
(<'FRUCTIFICATIONS') e. boggle 4 4 board 'FRUCTIFICATIONS'
(<'DISEMBARKATIONS') e. boggle 4 4 board 'DISEMBARKATIONS'
(<'DISCOUNTENANCES') e. boggle 4 4 board 'DISCOUNTENANCES'
